results = runtests({'adrcControllerMaskTest',...
    'observerOutputVariantTest',...
    'saturationVariantTest',...
    'deadTimeVariantTest',...
    'simpleExampleTest',...
    'simpleExampleExtendedTest',...
    'dcDcConverterTest',...
    'tanksTest',...
    'dcMotorTest',...
    'tclabTempControlTest'...
});