function controlSignal = stateFeedbackRobustController(controlError,...
        dynamicsOrder,...
        inputGainParameter,...
        controllerBandwidth,...
        estimatedExtendedState)
    
    extendedK = poly(-controllerBandwidth * ones(1, dynamicsOrder));
    K = extendedK(2:end);
    
    controlSignal = 1/inputGainParameter * (estimatedExtendedState(end) + ...
            K * [controlError; estimatedExtendedState(2:end-1)]);
end