function controlSignal = stateFeedbackRobustController(controlError,...
        inputGainParameter,...
        controllerBandwidth,...
        estimatedExtendedState,...
        dynamicsOrder)
   
    K = calculateControllerGain(controllerBandwidth, dynamicsOrder);
    
    controlSignal = 1/inputGainParameter * (estimatedExtendedState(end) + ...
            K * [controlError; estimatedExtendedState(2:end-1)]);
end

function controllerGain = calculateControllerGain(controllerBandwidth, dynamicsOrder)
    extendedControllerGain = poly(-controllerBandwidth * ones(1, dynamicsOrder));
    controllerGain = extendedControllerGain(2:end);
end
