function estimatedExtendedStateDerivative = linearExtendedStateObserver(controlError, controlSignal, dynamicsOrder, inputGainParameter, observerBandwidth, previousEstimatedExtendedState)
    A = [zeros(dynamicsOrder,1), eye(dynamicsOrder);...
        zeros(1,dynamicsOrder+1)];
    B = [zeros(dynamicsOrder-1,1); -inputGainParameter; 0];...
        extendedL = poly(-observerBandwidth * ones(1, dynamicsOrder+1))';
    L = extendedL(2:end);
    
    estimatedExtendedStateDerivative = A * previousEstimatedExtendedState +...
        B * controlSignal +...
        L * (controlError - previousEstimatedExtendedState(1));
end